### ISSUE TITLE
Please include PDF information on README.md, move release notes to CHANGELOG

### ISSUE THREAD

**Issue by MagicFab** [bmullan/ciab-remote-desktop-obsoleted-by-v5#12]
The PDF at https://github.com/bmullan/ciab-remote-desktop/blob/master/CIAB%20-%20README.pdf has complete and interesting details on what CIAB is, its requirements and installation.

It would be useful to move such information to README.md which currently only has a short explanation and take the release note and move them to a more appropriate document like CHANGELOG.

**Comment by bmullan** [comment]
Thanks for taking a look at my project !

I agree with your suggestion about the "Release" notes and moving them to a CHANGELOG file.

However, on the README.PDF I don't think I would want that to be the GitHub repositories README as that PDF is very long.   I would rather keep the Repository README separate and more of a 
_Summary_  of the project.  

Also, having the README.PDF separate I can continue to edit it locally with LibreWriter and then just export as a PDF & upload to GitHub.

Lastly,  the users can download the README.PDF and have it available offline already formatted.

But thanks for taking the time to provide input!

I'll try to get the Release notes moved later this week.

Brian

**Comment by MagicFab** [comment]
Sorry I wasn't clear. For a first-time visitor it's expected to see what this project is about in the first paragraph of the README, not on page 6 of a PDF which is unusual on this kind of project.

It would be most  useful to come up with a 1-2 paragraph summary explanation of what CIAB is and what problem it solves, most importantly why / how it uses Apache Guacamole.

For example (adjust/correct as needed):

> CIAB ("Cloud-in-a-box") Remote Desktop is a server application that integrates and extends the Apache Guacamole clientless remote desktop gateway on a Ubuntu 18.04 LTS host with LXD. A number of web applications can be easily deployed with server scripts.

> Using only a web browser that supports HTML5, users can connect to this web interface and access web applications and the Ubuntu Mate desktop as pre-configured and authorized by the CIAB administrator.
> 
> The initial installation configures two Linux containers:
> * CIAB-GUAC : An LXD container including Apache Guacamole and nested remotely-accesible 
> LXD-containers
> * CN1 : A nested LXD container in CIAB-GUAC including Ubuntu Mate, accessible via RDP using the CIAB web front-end.

**Comment by bmullan** [comment]
Fabian

Thanks for the comments.
Take a look at the updated README.md content and see if it reads better now.

Brian
